import { useEffect, useRef, useState } from 'react';
import { Aperture, ArrowUpRight, Box, Camera, Check, ChevronDown, CircleHelp, Crosshair, Download, Focus, Lightbulb, Maximize2, Move3D, Palette, RotateCcw, Rotate3D, SlidersHorizontal, Sun, UserRound } from 'lucide-react';
import { eulerToQuat, getTransform, lookAt, makePortraitScene, quatToEuler, withTransform } from './domain/scene';
import type { SceneDocument, Selection, Transform, Vec3 } from './domain/scene';
import { StudioRenderer } from './rendering/StudioRenderer';
import type { FrameStats } from './rendering/StudioRenderer';
import { NumberField, Range, Section } from './components/Controls';

const swatches=['#887b6f','#e8e2d8','#536b79','#444b48','#aa6f57','#26282c'];
const names={softbox:'120cm Softbox',camera:'Camera',model:'Humanoid'};
const defaultStats:FrameStats={ms:0,triangles:0,calls:0,samples:9,frames:0};
export default function App(){
  const [scene,setScene]=useState(makePortraitScene),[selected,setSelected]=useState<Selection>('softbox'),[mode,setMode]=useState<'translate'|'rotate'>('translate');
  const [stats,setStats]=useState(defaultStats),[error,setError]=useState(''),[help,setHelp]=useState(false),[toast,setToast]=useState(''),[hex,setHex]=useState(scene.environment.backgroundColor);
  const host=useRef<HTMLDivElement>(null),studio=useRef<HTMLDivElement>(null),preview=useRef<HTMLDivElement>(null),engine=useRef<StudioRenderer|null>(null);
  const current=useRef(scene);current.current=scene;
  const selection=useRef(selected);selection.current=selected;
  function change(fn:(s:SceneDocument)=>SceneDocument){setScene(s=>fn(s));}
  function transform(s:Selection,t:Transform){change(old=>withTransform(old,s,t));}
  useEffect(()=>{
    if(!host.current||!studio.current||!preview.current)return;
    try{engine.current=new StudioRenderer(host.current,studio.current,preview.current,current.current,{transform:(id,t)=>setScene(old=>withTransform(old,id,t)),select:setSelected,stats:setStats,error:setError});}
    catch(e){setError(`無法建立 3D 預覽：${e instanceof Error?e.message:String(e)}。請使用支援 WebGL 2 的瀏覽器。`);}
    return()=>{engine.current?.dispose();engine.current=null;};
  },[]);
  useEffect(()=>{engine.current?.update(scene);},[scene]);
  useEffect(()=>{engine.current?.select(selected);},[selected]);
  useEffect(()=>{engine.current?.mode(mode);},[mode]);
  useEffect(()=>{setHex(scene.environment.backgroundColor);},[scene.environment.backgroundColor]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='w')setMode('translate');if(e.key.toLowerCase()==='e')setMode('rotate');if(e.key==='Escape'){engine.current?.cancelDrag();setHelp(false);}if(e.key.toLowerCase()==='f')engine.current?.resetView();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const light=scene.lights[0],t=getTransform(scene,selected),angles=quatToEuler(t.quaternion);
  const dist=Math.hypot(light.transform.positionM[0]-scene.model.transform.positionM[0],light.transform.positionM[1]-1.4,light.transform.positionM[2]-scene.model.transform.positionM[2]);
  function updateCamera(p:Partial<SceneDocument['camera']>){change(s=>({...s,camera:{...s.camera,...p}}));}
  function updateLight(p:Partial<SceneDocument['lights'][0]>){change(s=>({...s,lights:[{...s.lights[0],...p}]}));}
  function setBackground(color:string){if(!/^#[\da-f]{6}$/i.test(color))return;change(s=>({...s,environment:{...s.environment,backgroundColor:color,floorColor:color}}));}
  function aim(){const p=getTransform(scene,selected).positionM;const target:Vec3=[scene.model.transform.positionM[0],scene.model.transform.positionM[1]+1.4*scene.model.heightCm/175,scene.model.transform.positionM[2]];if(Math.hypot(...p.map((n,i)=>n-target[i]))<.1){setToast('物件太接近目標，請先移開。');return;}transform(selected,{...t,quaternion:lookAt(p,target)});}
  function reset(){setScene(makePortraitScene());setSelected('softbox');setMode('translate');engine.current?.resetView();setToast('Portrait scene 已重設');}
  function exportScene(){const data=JSON.stringify({...scene,updatedAt:new Date().toISOString()},null,2);const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='portrait-lighting.scene.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('場景 JSON 已匯出');}
  return <div className="app-shell">
    <header className="app-header"><div className="brand"><div className="brand-icon"><Aperture size={23}/></div><strong>LUMA<span>STUDIO</span></strong><span className="prototype">PROTOTYPE 01</span></div><div className="project-name"><span className="project-dot"/>Portrait study<span className="slash">/</span><span>Untitled session</span></div><div className="header-actions"><button onClick={()=>setHelp(!help)} aria-label="操作說明"><CircleHelp size={17}/></button><button onClick={reset} className="reset"><RotateCcw size={14}/>Reset Scene</button><button onClick={exportScene} className="export"><Download size={14}/>Export scene</button></div></header>
    <div className="workspace-heading"><div><span className="eyebrow">YOUR LIGHTING WORKSPACE</span><h1>Shape the light.</h1></div><p>移動燈光，探索每一種可能。<span><i/> LIVE CAMERA PREVIEW</span></p></div>
    <div className="workspace">
      <div className="views-container" ref={host}>
        <div className="views-grid">
          <section className="view-panel studio-panel"><div className="view-heading"><span><Box size={15}/>Studio View <small>佈光空間</small></span><button title="還原編輯視角 F" onClick={()=>engine.current?.resetView()}><Maximize2 size={14}/></button></div><div ref={studio} className="studio-surface" data-testid="studio-view"><div className="studio-chips"><span>Perspective</span><span>1 grid = 0.5 m</span></div><div className="axis-key"><b>X</b><b>Y</b><b>Z</b></div><div className="studio-hint">拖動彩色軸移動物件 · 空白處拖曳環繞 · 滾輪縮放</div></div><div className="view-footer"><span className="selection-dot"/>{names[selected]} selected<span className="spacer"/><button className={mode==='translate'?'active':''} aria-label="移動工具 W" aria-pressed={mode==='translate'} onClick={()=>setMode('translate')}><Move3D size={14}/>Move <kbd>W</kbd></button><button className={mode==='rotate'?'active':''} aria-label="旋轉工具 E" aria-pressed={mode==='rotate'} onClick={()=>setMode('rotate')}><Rotate3D size={14}/>Rotate <kbd>E</kbd></button></div></section>
          <section className="view-panel preview-panel"><div className="view-heading"><span><Camera size={15}/>Camera Preview</span><span className="live"><i/>LIVE</span></div><div className="preview-surface" ref={preview} data-testid="camera-preview"><div className="frame-corner tl"/><div className="frame-corner br"/><div className="preview-watermark">PORTRAIT / 01</div></div><div className="view-footer camera-footer"><span>{scene.camera.focalLengthMm} mm</span><span>f/{scene.camera.fNumber}</span><span>1/{Math.round(1/scene.camera.shutterSeconds)} s</span><span>ISO {scene.camera.iso}</span><span className="spacer"/><small>FULL FRAME · 3:2</small></div></section>
        </div>
        {error&&<div className="error-panel" role="alert"><strong>預覽暫時無法使用</strong><p>{error}</p><button onClick={exportScene}>匯出目前場景</button><button onClick={()=>window.location.reload()}>重新載入</button></div>}
        <div className="bottom-strip"><span><Sun size={14}/> {light.source.mode==='continuous'?'Continuous light':'Strobe capture'} <b>·</b> Relative exposure</span><span>{stats.frames>0?'RENDERING READY':'INITIALIZING'}<i/></span></div>
      </div>
      <aside className="inspector">
        <div className="inspector-heading"><SlidersHorizontal size={16}/><span>Scene controls</span><small>01</small></div>
        <Section title="場景物件" badge="3 OBJECTS"><div className="object-list">{(['softbox','camera','model'] as Selection[]).map((id,i)=><button key={id} aria-label={`選取 ${names[id]}`} className={selected===id?'selected':''} onClick={()=>setSelected(id)}>{id==='softbox'?<Lightbulb size={16}/>:id==='camera'?<Camera size={16}/>:<UserRound size={16}/>}<span>{id==='softbox'?`${Math.round(light.modifier.widthM*100)}cm Softbox`:names[id]}<small>{['Key light · LED / Strobe','Full frame · 36 × 24 mm','Procedural study model'][i]}</small></span>{selected===id?<span className="object-active"/>:<ChevronDown size={12}/>}</button>)}</div></Section>
        <Section title={selected==='softbox'?'燈光設定':selected==='camera'?'鏡頭設定':'人物設定'} icon={selected==='softbox'?<Sun size={14}/>:selected==='camera'?<Camera size={14}/>:<UserRound size={14}/>}>
          {selected==='softbox'?<>
            <div className="mode-switch"><button className={light.source.mode==='continuous'?'active':''} onClick={()=>updateLight({fixtureId:'generic-led-200',source:{mode:'continuous',dimmerPercent:70,temperatureK:light.source.temperatureK}})}>Continuous</button><button className={light.source.mode==='strobe'?'active':''} onClick={()=>{change(s=>({...s,camera:{...s.camera,shutterSeconds:Math.max(1/200,s.camera.shutterSeconds)},lights:[{...s.lights[0],fixtureId:'generic-strobe-500',source:{mode:'strobe',powerEv:-1,temperatureK:s.lights[0].source.temperatureK}}]}));setToast('閃燈拍攝模式：快門限制在 1/200s 以內');}}>Strobe</button></div>
            {light.source.mode==='continuous'?<Range label="Power" value={light.source.dimmerPercent} min={0} max={100} unit="%" onChange={v=>updateLight({source:{...light.source,mode:'continuous',dimmerPercent:v}})}/>:<Range label="Power EV" value={light.source.powerEv} min={-6} max={0} step={1/3} unit="EV" onChange={v=>updateLight({source:{...light.source,mode:'strobe',powerEv:v}})}/>}
            <Range label="Color temperature" value={light.source.temperatureK} min={3200} max={6500} step={100} unit="K" onChange={v=>updateLight({source:{...light.source,temperatureK:v}})}/><div className="temperature-legend"><span>Warm</span><div/><span>Cool</span></div>
            <Range label="Softbox size" value={light.modifier.widthM*100} min={30} max={180} step={5} unit="cm" onChange={v=>updateLight({modifier:{...light.modifier,widthM:v/100,heightM:v/100}})}/><p className="micro-note">發光面越大，影緣越柔和。總輸出維持相同。</p>
          </>:selected==='camera'?<><p className="micro-note">固定 full-frame。移動相機改變透視，焦距改變畫角。</p><div className="lens-presets">{[35,50,85,105].map(f=><button key={f} className={scene.camera.focalLengthMm===f?'active':''} onClick={()=>updateCamera({focalLengthMm:f})}>{f}<small>mm</small></button>)}</div></>:<><Range label="Model height" value={scene.model.heightCm} min={150} max={200} unit="cm" onChange={v=>change(s=>({...s,model:{...s.model,heightCm:v}}))}/><Range label="Model turn" value={Math.round(quatToEuler(scene.model.transform.quaternion)[1])} min={-80} max={80} unit="°" onChange={v=>transform('model',{...scene.model.transform,quaternion:eulerToQuat([0,v,0])})}/><p className="micro-note">原創程序式人台，用於觀察鼻影、臉頰與身體受光。</p></>}
        </Section>
        <Section title="Transform" badge="WORLD"><div className="transform-label">Position <small>meters</small></div><div className="xyz-fields">{['X','Y','Z'].map((axis,i)=><NumberField key={axis} label={`Position ${axis}`} value={t.positionM[i]} min={i===1?(selected==='model'?0:.25):-4} max={6} onChange={v=>{const p=[...t.positionM] as Vec3;p[i]=v;transform(selected,{...t,positionM:p});}}/>)}</div><div className="transform-label">Rotation <small>degrees</small></div><div className="xyz-fields">{['X','Y','Z'].map((axis,i)=><NumberField key={axis} label={`Rotation ${axis}`} value={angles[i]} min={-180} max={180} step={5} onChange={v=>{const r=[...angles] as Vec3;r[i]=v;transform(selected,{...t,quaternion:eulerToQuat(r)});}}/>)}</div>{selected!=='model'&&<button className="aim-button" onClick={aim}><Crosshair size={14}/>Aim at model<ArrowUpRight size={13}/></button>}</Section>
        <div className="inspector-note"><span className="material-dot"/>近似光影 · 無間接反射或皮膚 SSS</div>
      </aside>
    </div>
    <div className="lower-controls"><Section title="Camera & exposure" icon={<Aperture size={16}/>} badge="MANUAL"><div className="camera-controls"><label>Focal length<select aria-label="Focal length" value={scene.camera.focalLengthMm} onChange={e=>updateCamera({focalLengthMm:+e.target.value})}>{[35,50,85,105].map(f=><option key={f} value={f}>{f} mm</option>)}</select></label><label>ISO<select aria-label="ISO" value={scene.camera.iso} onChange={e=>updateCamera({iso:+e.target.value})}>{[100,200,400,800,1600,3200,6400].map(n=><option key={n}>{n}</option>)}</select></label><label>Aperture<select aria-label="Aperture" value={scene.camera.fNumber} onChange={e=>updateCamera({fNumber:+e.target.value})}>{[1.4,2,2.8,4,5.6,8,11,16,22].map(n=><option key={n} value={n}>f/{n}</option>)}</select></label><label>Shutter speed<select aria-label="Shutter speed" value={scene.camera.shutterSeconds} onChange={e=>updateCamera({shutterSeconds:+e.target.value})}>{[15,30,60,125,200,250,500,1000].map(n=><option key={n} value={1/n} disabled={light.source.mode==='strobe'&&n>200}>1/{n} s</option>)}</select></label></div><p className="micro-note">{light.source.mode==='continuous'?'持續燈：ISO、光圈與快門皆影響曝光。':'閃燈：同步範圍內，快門不改變閃光曝光。'} 景深暫不模擬。</p></Section>
    <Section title="Background" icon={<Palette size={16}/>} badge="SEAMLESS"><div className="background-controls"><div className="swatches">{swatches.map(color=><button key={color} style={{background:color}} aria-label={`背景 ${color}`} aria-pressed={scene.environment.backgroundColor===color} onClick={()=>setBackground(color)}>{scene.environment.backgroundColor===color&&<Check size={14}/>}</button>)}</div><label className="color-picker" title="自訂背景色"><input aria-label="Background color" type="color" value={scene.environment.backgroundColor} onChange={e=>setBackground(e.target.value)}/><Palette size={15}/></label><input className="hex-input" aria-label="Background HEX" value={hex} maxLength={7} onChange={e=>{setHex(e.target.value);setBackground(e.target.value);}} onBlur={()=>setHex(scene.environment.backgroundColor)}/></div><p className="micro-note">背景及地板即時同步；畫面色彩會受到光線與曝光影響。</p></Section></div>
    <footer className="status-bar"><span><span className="ready-dot"/>{error?'Preview unavailable':'All changes are live'}</span><span>Softbox → model <b>{dist.toFixed(2)} m</b><span className="sep">/</span><Focus size={12}/>{scene.camera.focalLengthMm}mm</span><span title="CPU render submission time, not GPU FPS" data-testid="render-stats">{stats.ms.toFixed(1)} ms CPU · {stats.samples} shadow samples<span className="sep">/</span>WebGL 2</span></footer>
    {toast&&<div className="toast" role="status"><Check size={14}/>{toast}</div>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><div className="help-modal" role="dialog" aria-modal="true" aria-label="操作說明" onClick={e=>e.stopPropagation()}><span className="eyebrow">GET STARTED</span><h2>你的第一個佈光實驗</h2><p>選取 Softbox，拖動紅、綠、藍軸調整位置。綠軸控制高度。按 E 切換旋轉環，或在右側輸入精確數值。</p><p>Camera Preview 永遠使用拍攝相機。Studio View 的環繞不會改變照片構圖。</p><p>改變 Softbox size、距離與 Power，觀察臉部影緣及明暗。下方可調焦距、曝光和背景。</p><p><kbd>W</kbd> 移動　<kbd>E</kbd> 旋轉　<kbd>F</kbd> 還原視角　<kbd>Esc</kbd> 取消拖動</p><button className="export" onClick={()=>setHelp(false)}>開始探索 <ArrowUpRight size={15}/></button></div></div>}
  </div>;
}
